// Field/section descriptors for every table the API exposes. Field shape:
// { name, label?, type, optionsKey? } where type is one of
//   text (default) | number | date | tel
//   enum   -> real dropdown, for closed sets (gender, relation, category…)
//   select -> free text with suggestions, where new values are legitimate
//             (institute names, syllabuses, grades)
// `label` defaults to a humanized version of `name` when omitted.

function f(name, extra) {
  return { name, ...extra };
}

export const CONTACT_MASTER = {
  path: "/contact-master/",
  pk: "prfml_id",
  title: "Family",
  sections: [
    {
      title: "Identity & Address",
      fields: [
        f("fullname", { label: "Full Name" }),
        f("known_as"),
        f("gender", { type: "enum", optionsKey: "gender" }),
        f("dob", { label: "Date of Birth", type: "date" }),
        f("address"),
        f("panchayath", { label: "Panchayath" }),
        f("ward", { type: "number" }),
        f("house_no", { label: "House No." }),
        f("taluk"),
        f("mahallu"),
        f("post"),
        f("pin", { label: "PIN" }),
        f("district"),
        f("area"),
      ],
    },
    {
      title: "Contact & Financial",
      fields: [
        f("mobile", { type: "tel" }),
        f("whatsapp", { type: "tel" }),
        f("gpay", { label: "GPay" }),
        f("occupation"),
        f("salary"),
        f("bank_name", { label: "Bank Name" }),
        f("bank_branch", { label: "Bank Branch" }),
        f("bank_ac", { label: "Bank A/C No." }),
        f("ration_card", { label: "Ration Card" }),
        f("ration", { label: "Ration Amount", type: "number" }),
      ],
    },
    {
      title: "ID Documents",
      fields: [
        f("idx_id", { label: "PID", type: "number" }),
        f("oldid", { label: "Old ID" }),
        f("srl_no", { label: "Srl. No.", type: "number" }),
        f("old_srl", { label: "Old Srl. No.", type: "number" }),
        f("aadhar_no", { label: "Aadhar No." }),
        f("election_id", { label: "Election ID" }),
      ],
    },
    {
      title: "Family",
      fields: [
        f("religion", { type: "enum", optionsKey: "religion" }),
        f("qualification"),
        f("blood_group", { label: "Blood Group", type: "enum", optionsKey: "bloodGroup" }),
        f("marital_status", { label: "Marital Status", type: "enum", optionsKey: "maritalStatus" }),
        f("spouse_name", { label: "Spouse Name" }),
        f("marital_status_discr", { label: "Marital Status (Reason)" }),
        f("father_name", { label: "Father Name" }),
        f("father_mobile", { label: "Father Mobile", type: "tel" }),
        f("mother_name", { label: "Mother Name" }),
        f("mother_mobile", { label: "Mother Mobile", type: "tel" }),
        f("guard_name", { label: "Guardian Name" }),
        f("guard_mobile", { label: "Guardian Mobile", type: "tel" }),
      ],
    },
    {
      title: "Status",
      fields: [
        f("pr_category", { label: "Category", type: "enum", optionsKey: "prCategory" }),
        f("pr_category_old", { label: "Category (Old)" }),
        f("social_status", { label: "Social Status", type: "enum", optionsKey: "socialStatus" }),
        f("health_status", { label: "Health Status", type: "enum", optionsKey: "healthStatus" }),
        f("health_condition", { label: "Health Condition" }),
        f("approved", { type: "enum", optionsKey: "approved" }),
        f("exclusion_reason", { label: "Exclusion Reason" }),
        f("joined_year", { label: "Joined Year" }),
        f("remark"),
      ],
    },
  ],
};

export const DEPENDENT_MASTER = {
  path: "/dependent-master/",
  pk: "dpid",
  title: "Dependent",
  sections: [
    {
      title: "Personal",
      fields: [
        f("fullname", { label: "Full Name" }),
        f("gender", { type: "enum", optionsKey: "gender" }),
        f("dob", { label: "Date of Birth", type: "date" }),
        f("relation", { type: "enum", optionsKey: "relation" }),
        f("ambition"),
        f("hobbies"),
      ],
    },
    {
      title: "School / College",
      fields: [
        f("edu_status", { label: "Edu. Status", type: "enum", optionsKey: "eduStatus" }),
        f("inst_type", { label: "Type", type: "enum", optionsKey: "instType" }),
        f("inst_name", { label: "Institute Name" }),
        f("inst_grade", { label: "Grade", type: "select", optionsKey: "instGrade" }),
        f("inst_division", { label: "Division" }),
        f("inst_syllabus", { label: "Syllabus" }),
        f("inst_medium", { label: "Medium", type: "enum", optionsKey: "instMedium" }),
        f("inst_academic_yr", { label: "Academic Year" }),
        f("trnsp_fee", { label: "Transport Fee", type: "number" }),
        f("fav_subject", { label: "Favourite Subject" }),
        f("dif_subject", { label: "Difficult Subject" }),
      ],
    },
    {
      title: "Madrasa Education",
      fields: [
        f("madrasa_grade", { label: "Grade" }),
        f("madrasa_name", { label: "Name" }),
        f("madrasa_syllabus", { label: "Syllabus" }),
        f("madrasa_academic_yr", { label: "Academic Year" }),
      ],
    },
    {
      title: "Contact & Health",
      fields: [
        f("mobile", { type: "tel" }),
        f("whatsapp", { type: "tel" }),
        f("occupation"),
        f("salary"),
        f("blood_group", { label: "Blood Group", type: "enum", optionsKey: "bloodGroup" }),
        f("aadhar_no", { label: "Aadhar No." }),
        f("election_id", { label: "Election ID" }),
        f("marital_status", { label: "Marital Status", type: "enum", optionsKey: "maritalStatus" }),
        f("spouse_name", { label: "Spouse Name" }),
        f("marital_status_discr", { label: "Marital Status (Reason)" }),
        f("health_condition", { label: "Health Condition" }),
      ],
    },
  ],
};

// Tracking tables: flat field lists. `path`/`pk` used by RelatedRecordsPanel;
// the foreign key column (prfml_id or dpid) is injected/hidden by the panel,
// so it is intentionally left out of these field lists.
export const TRACKERS = {
  communicationTracking: {
    path: "/communication-tracking/",
    pk: "id",
    title: "Communications",
    filterColumn: "prfml_id",
    fields: [
      f("comm_date", { label: "Date", type: "date" }),
      f("comm_time", { label: "Time" }),
      f("comm_executive", { label: "Executive" }),
      f("comm_reason", { label: "Reason" }),
      f("comm_outcome", { label: "Outcome" }),
      f("comm_type", { label: "Type" }),
      f("comm_method", { label: "Method" }),
    ],
  },
  healthIssueTracking: {
    path: "/health-issue-tracking/",
    pk: "prfml_hi_id",
    title: "Health & Charity Records",
    filterColumn: "prfml_id",
    fields: [
      f("hi_type", { label: "Type" }),
      f("hi_descr", { label: "Description" }),
      f("hi_date", { label: "Date", type: "date" }),
      f("hi_clinic", { label: "Clinic" }),
      f("hi_clinic_type", { label: "Clinic Type" }),
      f("hi_clinic_stream", { label: "Clinic Stream" }),
      f("hi_executive", { label: "Executive" }),
      f("hi_amount", { label: "Amount", type: "number" }),
      f("hi_update", { label: "Update" }),
    ],
  },
  attendanceTracking: {
    path: "/attendance-tracking/",
    pk: "id",
    title: "Attendance",
    filterColumn: "prfml_id",
    fields: [
      f("event_id", { label: "Event ID", type: "number" }),
      f("attend_date", { label: "Date", type: "date" }),
      f("attend_time", { label: "Time" }),
    ],
  },
  visitTracking: {
    path: "/visit-tracking/",
    pk: "id",
    title: "Visits",
    filterColumn: "prfml_id",
    fields: [
      f("visit_date", { label: "Date", type: "date" }),
      f("visit_time", { label: "Time" }),
      f("visit_purpose", { label: "Purpose" }),
      f("visit_executive", { label: "Executive" }),
      f("visit_outcome", { label: "Outcome" }),
    ],
  },
  noorulQuranTracking: {
    path: "/noorul-quran-tracking/",
    pk: "id",
    title: "Noorul Quran",
    filterColumn: "prfml_id",
    fields: [
      f("batch"),
      f("exam1", { label: "Exam 1", type: "number" }),
      f("exam2", { label: "Exam 2", type: "number" }),
      f("exam3", { label: "Exam 3", type: "number" }),
      f("exam4", { label: "Exam 4", type: "number" }),
      f("exam5", { label: "Exam 5", type: "number" }),
      f("exam6", { label: "Exam 6", type: "number" }),
      f("exam7", { label: "Exam 7", type: "number" }),
      f("final", { label: "Final", type: "number" }),
    ],
  },
  academicTracking: {
    path: "/academic-tracking/",
    pk: "id",
    title: "Academic Records",
    filterColumn: "dpid",
    fields: [
      f("academic_yr", { label: "Academic Year" }),
      f("exam_period", { label: "Exam Period" }),
      f("exam_date", { label: "Exam Date", type: "date" }),
      f("first_lang_type", { label: "1st Language Type" }),
      f("first_lang", { label: "1st Language" }),
      f("malayalam2", { label: "Malayalam" }),
      f("english", { label: "English" }),
      f("hindi", { label: "Hindi" }),
      f("social_science", { label: "Social Science" }),
      f("basic_science", { label: "Basic Science" }),
      f("physics", { label: "Physics" }),
      f("chemistry", { label: "Chemistry" }),
      f("biology", { label: "Biology" }),
      f("maths", { label: "Maths" }),
      f("overall", { label: "Overall" }),
      f("total_marks", { label: "Total Marks", type: "number" }),
    ],
  },
  dependentCommunicationTracking: {
    path: "/dependent-communication-tracking/",
    pk: "id",
    title: "Communication Tracking",
    filterColumn: "dpid",
    fields: [
      f("comm_date", { label: "Date", type: "date" }),
      f("comm_time", { label: "Time" }),
      f("comm_executive", { label: "Executive" }),
      f("comm_person", { label: "Person" }),
      f("comm_person_mobile", { label: "Person Mobile", type: "tel" }),
      f("comm_reason", { label: "Reason" }),
      f("comm_outcome", { label: "Outcome" }),
      f("comm_type", { label: "Type" }),
      f("comm_method", { label: "Method" }),
    ],
  },
  dependentFeedbackTracking: {
    path: "/dependent-feedback-tracking/",
    pk: "id",
    title: "Feedback",
    filterColumn: "dpid",
    fields: [
      f("fml_support", { label: "Family Support" }),
      f("fml_fdb_study_time", { label: "Study Time" }),
      f("fml_fdb_social_media_time", { label: "Social Media Time" }),
      f("fml_fdb_friends_time", { label: "Friends Time" }),
      f("fml_fdb_mobile_game_time", { label: "Mobile Game Time" }),
      f("fml_fdb_physical_game_time", { label: "Physical Game Time" }),
      f("fml_fdb_relegious_time", { label: "Religious Time" }),
      f("fml_fdb_behaviour_to_parent", { label: "Behaviour to Parent" }),
      f("fml_fdb_behaviour_to_sibling", { label: "Behaviour to Sibling" }),
      f("fml_fdb_health_issues", { label: "Health Issues" }),
      f("schl_fdb_character", { label: "School: Character" }),
      f("schl_fdb_study_quality", { label: "School: Study Quality" }),
      f("schl_fdb_friends_time", { label: "School: Friends Time" }),
      f("schl_fdb_attendace", { label: "School: Attendance" }),
      f("schl_fdb_extra_activities", { label: "School: Extra Activities" }),
    ],
  },
  dependentActivityTracking: {
    path: "/dependent-activity-tracking/",
    pk: "id",
    title: "Other Activity",
    filterColumn: "dpid",
    fields: [
      f("act_date", { label: "Date", type: "date" }),
      f("act_type", { label: "Type" }),
      f("act_description", { label: "Description" }),
      f("act_feedback", { label: "Feedback" }),
      f("act_person", { label: "Person" }),
    ],
  },
  dependentEduTracking: {
    path: "/dependent-edu-tracking/",
    pk: "eduid",
    title: "Education History",
    filterColumn: "dpid",
    fields: [
      f("inst_academic_yr", { label: "Academic Year" }),
      f("inst_type", { label: "Type", type: "enum", optionsKey: "instType" }),
      f("inst_name", { label: "Institute Name" }),
      f("inst_grade", { label: "Grade", type: "select", optionsKey: "instGrade" }),
      f("inst_syllabus", { label: "Syllabus" }),
      f("inst_medium", { label: "Medium", type: "enum", optionsKey: "instMedium" }),
      f("madrasa_academic_yr", { label: "Madrasa Academic Year" }),
      f("madrasa_grade", { label: "Madrasa Grade" }),
      f("madrasa_name", { label: "Madrasa Name" }),
      f("madrasa_syllabus", { label: "Madrasa Syllabus" }),
    ],
  },
};

export const FAMILY_TABS = [
  { key: "dependents", label: "Dependents" },
  { key: "communicationTracking", label: "Communications" },
  { key: "healthIssueTracking", label: "Health & Charity Records" },
  { key: "attendanceTracking", label: "Attendance" },
  { key: "visitTracking", label: "Visits" },
  { key: "noorulQuranTracking", label: "Noorul Quran" },
];

export const DEPENDENT_TABS = [
  { key: "academicTracking", label: "Academic Records" },
  { key: "dependentCommunicationTracking", label: "Communication Tracking" },
  { key: "dependentFeedbackTracking", label: "Feedback" },
  { key: "dependentActivityTracking", label: "Other Activity" },
  { key: "dependentEduTracking", label: "Education History" },
];
